config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :expenditures
  root 'expenditures#index'
end

app/models/expenditure.rb
class Expenditure < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :expenditures
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/expenditures_controller.rb
class ExpendituresController < ApplicationController
  before_action :check_user, only: [:edit, :update]

  def index
    @expenditures = Expenditure.all.order(purchase_date: :desc)
    # @expenditures = current_user.expenditures
  end

  def show
    @expenditure = Expenditure.find(params[:id])
  end

  def new
    @expenditure = Expenditure.new
  end

  def edit
    @expenditure = Expenditure.find(params[:id])
    # if current_user != @expenditure.user
    #   redirect_to expenditures_path
    # end
  end

  def create
    @expenditure = Expenditure.new(expenditure_params)
    @expenditure.user = current_user
    if @expenditure.save
      redirect_to expenditure_path(@expenditure)
    else
      redirect_to new_expenditure_path
    end
  end

  def update
    @expenditure = Expenditure.find(params[:id])
    if @expenditure.update(expenditure_params)
      redirect_to @expenditure
    else
      render 'edit'
    end
  end

  def destroy
    @expenditure = Expenditure.find(params[:id])
    @expenditure.destroy
    redirect_to expenditures_path
  end

  private
    #before action method
    def check_user
      unless current_user == Expenditure.find(params[:id]).user
        flash[:error] = "Insufficient permissions"
        redirect_to expenditures_path # halts request cycle
      end
    end

    def expenditure_params
      params.require(:expenditure).permit(:name, :price, :quantity, :purchase_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenditures_helper.rb
module ExpendituresHelper
  def same_user? user 
    current_user == user
  end
end


# <% if !same_user? expenditure.user %>
#           <p>You cannot change other's expenses </p>
# <% end %>

app/views/expenditures/_form.html.erb
<%= form_for @expenditure, :html => { :multipart => true } do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :price %><br>
    <%= f.number_field :price %>
  </p>
  <p>
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </p>
  <p>
    <%= f.label :purchase_date %><br>
    <%= f.date_field :purchase_date %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/expenditures/edit.html.erb
<h1>Edit Page</h1>

<%= render 'form' %>

<%= link_to "Back", expenditures_path %>

app/views/expenditures/index.html.erb
<h1>My Purchases</h1>

<table class="table table-striped">
  <tr>
    <th>
      Date
    </th>
    <th>
      Purchase
    </th>
    <th>
      Price
    </th>
    <th>
      Quantity
    </th>
    <th>
    </th>
  </tr>

  <% @expenditures.each do |expenditure| %>
      <tr>
        <td>
          <%= expenditure.purchase_date.to_date %>
        </td>
        <td>
          <%= expenditure.name %>
        </td>
        <td>
          R<%= expenditure.price %>
        </td>
        <td>
          <%= expenditure.quantity %>
        </td>
        <td>
          <%= link_to 'Expand', expenditure_path(expenditure) %>
        </td>
        <td>
          <% if current_user == expenditure.user %>
            <!-- get rid of data confirm box -->
            <%= link_to 'Edit', edit_expenditure_path(expenditure), data: { confirm: "You cannot edit other's expenses" } %>
          <% end %>
        </td>
        <td>
          <%= link_to 'Delete', expenditure_path(expenditure), method: :delete, data: { confirm: "Are you sure?" } %>
          <!-- best way to protect edit and delete? can only show those by user, but how to do it this way?-->
        </td>
    <% end %>
</table>

<%= link_to 'Add Purchase', new_expenditure_path %>

app/views/expenditures/new.html.erb
<h1>New Expenditure</h1>
<%= render 'form' %>

app/views/expenditures/show.html.erb
<h1><%= @expenditure.name %></h1>
<p>
  Date: <%= @expenditure.purchase_date.to_date %><br>
  Price: R<%= @expenditure.price %><br>
  Quantity: <%= @expenditure.quantity %><br>
</p>

<%= link_to 'back', expenditures_path %>

app/views/layouts/_alerts.erb
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/_nav.erb
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IxY02s03Brubudget</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p id="error"><%= flash[:error] %></p>
<%= render 'layouts/nav' %>
<%= render 'layouts/alerts' %>

<%= yield %>

</body>
</html>